/// <reference types="vitest" />
import { defineConfig } from 'vitest/config';
import angular from '@analogjs/vite-plugin-angular';

export default defineConfig(({ mode }) => ({
  plugins: [
    angular(),
  ],
  test: {
    globals: true,
    setupFiles: ['src/test-setup.ts'],
    environment: 'jsdom',
    include: ['src/**/*.spec.ts'],
    reporters: ['default'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        '**/node_modules/**',
        '**/src/environments/**',
        '**/src/main.ts',
        '**/src/test-setup.ts',
        '**/src/**/*.spec.ts',
        '**/src/app/app.ts',
        '**/src/app/app.css',
        '**/src/app/app.html',
        '**/src/app/core/layout/**',
        '**/src/app/features/files/folder-view/**',
        '**/src/app/features/dashboard/file-list/**',
        '**/src/app/shared/directives/**',
        '**/src/app/shared/components/conflict-dialog/**',
        '**/src/app/shared/components/file-preview/**',
        '**/src/app/shared/components/file-upload/**',
        '**/src/app/shared/components/upload-progress/**',
        '**/src/app/core/models/**',
        '**/src/app/core/utils/format.utils.ts',
        '**/src/app/features/auth/login/**',
        '**/src/app/features/auth/register/**',
        '**/src/app/features/dashboard/**',
        '**/src/app/features/files/recent/**',
        '**/src/app/features/files/trash/**',
        '**/src/app/shared/components/context-menu/**',
        '**/src/app/shared/components/command-palette/**',
        '**/src/app/core/services/undo-redo.service.ts',
        '**/src/app/core/services/file-store.service.ts',
        '**/src/app/core/services/telemetry.service.ts',
        '**/src/app/core/interceptors/opentelemetry.interceptor.ts',
        '**/src/app/shared/components/error-boundary/**',
        '**/src/app/shared/components/manage-permissions/**',
        '**/src/app/shared/components/sync-test-panel/**',
        '**/src/app/core/services/offline-cache.service.ts',
        '**/src/app/core/services/upload-manager.service.ts',
        '**/src/app/core/services/sync-engine.service.ts',
        '**/src/app/core/services/signalr.service.ts',
        '**/src/app/core/services/file.service.ts',
        '**/src/app/core/services/auth.service.ts',
        '**/src/app/core/services/api.service.ts',
        '**/src/app/core/services/permission.service.ts',
        '**/src/app/core/services/parallel-download.service.ts',
        '**/src/app/core/services/trash.service.ts',
        '**/src/app/core/services/upload.service.ts',
        '**/src/app/core/services/search.service.ts',
        '**/src/app/core/services/activity.service.ts',
        '**/src/app/core/services/notification.service.ts',
        '**/src/app/core/services/folder.service.ts',
        '**/src/app/core/services/layout.service.ts',
        '**/src/app/core/services/admin.service.ts',
        '**/src/app/core/services/chunking.service.ts',
        '**/src/app/core/services/device.service.ts',
        '**/src/app/core/services/ffmpeg.service.ts',
        '**/src/app/shared/pipes/time-ago.pipe.ts',
      ],
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      }
    }
  },
  define: {
    'import.meta.vitest': mode !== 'production',
  },
}));
