apiVersion: v1
kind: Secret
metadata:
  name: cloudstorage-secrets
  namespace: cloud-storage
type: Opaque
data:
  # Base64 encoded: Host=postgres-svc;Database=cloudstorage;Username=postgres;Password=postgres;Maximum Pool Size=100;Minimum Pool Size=10;Connection Idle Lifetime=300;
  ConnectionStrings__DefaultConnection: SG9zdD1wb3N0Z3Jlcy1zdmM7RGF0YWJhc2U9Y2xvdWRzdG9yYWdlO1VzZXJuYW1lPXBvc3RncmVzO1Bhc3N3b3JkPXBvc3RncmVzO01heGltdW0gUG9vbCBTaXplPTEwMDtNaW5pbXVtIFBvb2wgU2l6ZT0xMDtDb25uZWN0aW9uIElkbGUgTGlmZXRpbWU9MzAwOw==
  # Base64 encoded: guest
  RabbitMQ__UserName: Z3Vlc3Q=
  # Base64 encoded: guest
  RabbitMQ__Password: Z3Vlc3Q=
  # Base64 encoded: YourSuperSecretKeyForJwtAuthentication
  Jwt__Key: WW91clN1cGVyU2VjcmV0S2V5Rm9ySnd0QXV0aGVudGljYXRpb24=
  # Base64 encoded: minioadmin
  MINIO_ROOT_USER: bWluaW9hZG1pbg==
  # Base64 encoded: minioadmin
  MINIO_ROOT_PASSWORD: bWluaW9hZG1pbg==
  # Base64 encoded: minioadmin
  StorageProvider__MinIO__AccessKey: bWluaW9hZG1pbg==
  # Base64 encoded: minioadmin
  StorageProvider__MinIO__SecretKey: bWluaW9hZG1pbg==
  # Base64 encoded: postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=
